### ISSUE TITLE
本地测了一下，需要在header里面加一个cookie才能实现。 日期:2021-11-09

### ISSUE THREAD

**Issue by fengqiangzhao** [fugary/calibre-web-douban-api#1]
![image](https://user-images.githubusercontent.com/31373172/140888530-c3352979-4e44-43bb-819b-3f106a73a856.png)

**Comment by fengqiangzhao** [comment]
如图：dbcl2="xxxxxxxxxxxx"  可以手动登录豆瓣从cookie中获取

**Comment by fugary** [comment]
> 如图：dbcl2="xxxxxxxxxxxx" 可以手动登录豆瓣从cookie中获取

应该不用在header加东西，我的nas上的calibre-web已经用上了，本地跑也是可以的

**Comment by fengqiangzhao** [comment]
@fugary 我再次尝试确实可以了。不知道为什么第一次用的时候，https://www.douban.com/j/search  的结果是登录页。
