### ISSUE TITLE
下载封面时出错

### ISSUE THREAD

**Issue by Ahdw** [fugary/calibre-web-douban-api#11]
成功添加了NewDouban 的源，并且可以更新除封面外的所有元数据。
calibre-web 报错：下载封面时出错

手动尝试把豆瓣网页上，书籍封面的链接填写在元数据表格中，有的可以成功获取封面，有的不能，报同样的错：下载封面时出错。

**Comment by wodepig** [comment]
可能是豆瓣的限制.我用图床的链接就能正常下载,豆瓣就不行
