### ISSUE TITLE
calibre-web 豆瓣封面问题

### ISSUE THREAD

**Issue by undosh77** [fugary/calibre-web-douban-api#15]
calibre pc版的插件已更新豆瓣封面问题了。请问，docker版本的calibre-web DouBan.py 会更新吗？

**Comment by fugary** [comment]
有空看看，封面下载在calibre-web内部，可能要本地代理封面地址才行

**Comment by undosh77** [comment]
目前用chrome插件ModHeader，网页端可以显示。但是手机的话，因为无法安装插件，无解。calibre-web内部的话估计需要releas更新才有可能，但是这个不是国人发布的恐怕不会解决豆瓣了。

**Comment by fugary** [comment]
最新版已修复豆瓣封面下载失败的问题
