### ISSUE TITLE
使用最新版本的脚本，能看到豆瓣封面，但无法拉取

### ISSUE THREAD

**Issue by flamesky80** [fugary/calibre-web-douban-api#18]
23年12月
系统：威联通 NAS
安装模式：johngong的calibre-web docker。配置正常，可正常运行。
docker内的环境：
    calibre版本 0.6.21 python版本3.11.6 flask版本2.3.3  requests版本2.31.0

安装脚本后，进入获取元数据页面，可以看到new douban books这个tab。
能正常显示douban的书籍信息、包括封面、isbn、简介。
点击某个封面能正常获取除了封面之外的其他数据。
就是无法获得封面图。

**Comment by flamesky80** [comment]
补充：威联通系统的py版本为3.10

**Comment by xp9477** [comment]
修改DOUBAN_PROXY_COVER_HOST_URL

**Comment by xp9477** [comment]
> 23年12月 系统：威联通 NAS 安装模式：johngong的calibre-web docker。配置正常，可正常运行。 docker内的环境： calibre版本 0.6.21 python版本3.11.6 flask版本2.3.3 requests版本2.31.0
> 
> 安装脚本后，进入获取元数据页面，可以看到new douban books这个tab。 能正常显示douban的书籍信息、包括封面、isbn、简介。 点击某个封面能正常获取除了封面之外的其他数据。 就是无法获得封面图。


修改DOUBAN_PROXY_COVER_HOST_URL

**Comment by flamesky80** [comment]
> > 23年12月 系统：威联通 NAS 安装模式：johngong的calibre-web docker。配置正常，可正常运行。 docker内的环境： calibre版本 0.6.21 python版本3.11.6 flask版本2.3.3 requests版本2.31.0
> > 安装脚本后，进入获取元数据页面，可以看到new douban books这个tab。 能正常显示douban的书籍信息、包括封面、isbn、简介。 点击某个封面能正常获取除了封面之外的其他数据。 就是无法获得封面图。
> 
> 修改DOUBAN_PROXY_COVER_HOST_URL

谢谢！有效！！！
