### ISSUE TITLE
python版和PC版的插件对比，信息准确度较差。

### ISSUE THREAD

**Issue by flamesky80** [fugary/calibre-web-douban-api#19]
同一本书，在PC上使用Calibre，在NAS上使用Calibre-Web，NewDoubanBook插件获得的信息差别很大。
请问有可能给py版也加上douban cookies，提升准确度吗？

PC因为使用cookies的缘故，看起来更准确。
![image](https://github.com/user-attachments/assets/9d629c5a-b418-43f0-96b0-5a50b68cd1f1)

Calibre-Web版，最近经常搜不到。
![image](https://github.com/user-attachments/assets/7a2f99ce-b791-45b4-8fdc-8385c7036c6e)
搜到的情况下，信息也不准确。
![image](https://github.com/user-attachments/assets/a417d07b-f555-477a-9196-8fe98aaeb362)

**Comment by flamesky80** [comment]
我自己找到添加cookies的方法了。

**Comment by yanisliu** [comment]
> 我自己找到添加cookies的方法了。

请问如何操作呢？
