### ISSUE TITLE
.py文件放入provider后提示语法错误，整个calibre-web

### ISSUE THREAD

**Issue by refined-fish** [fugary/calibre-web-douban-api#3]
![OMQ W `~W3}NT3SSE4HR4A0](https://user-images.githubusercontent.com/93998080/147350348-387f594f-4ac3-48f2-948e-aa2834913829.png)

**Comment by fugary** [comment]
打开NewDouban.py看看内容是否是正常的python

**Comment by refined-fish** [comment]
一打开还真是，变成了没看懂的东西，非常感谢你的回复！




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Gary ***@***.***&gt;; 
发送时间: 2021年12月24日(星期五) 晚上7:59
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [fugary/calibre-web-douban-api] .py文件放入provider后提示语法错误，整个calibre-web (Issue #3)





 
打开NewDouban.py看看内容是否是正常的python
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by refined-fish** [comment]
问题解决了，目前使用正常
![02357A83](https://user-images.githubusercontent.com/93998080/147351471-a4ac0257-6313-46a4-b65b-7c85b3b5d83f.png)
