### ISSUE TITLE
把.py文件挂载进群晖docker，就启动不了。。

### ISSUE THREAD

**Issue by toniexly** [fugary/calibre-web-douban-api#4]
描述如题，用的镜像是linuxserver的，挂载.py文件到 /app/calibre-web/cps/metadata_provider/NewDouban.py。容器连不上。。不知是挂载目录有误，还是我忘了做哪一步。。

05:55:03 Traceback(most recent call last):
05:55:03 File"/app/calibre-web/cps.py",line 40,in<module>
05:55:03 from cps.search_metadata import meta
05:55:03 File"/app/calibre-web/cps/search_metadata.py",line 48,in<module>
05:55:03 importlib.import_module("cps.metadata_provider."+ a)
05:55:03 File"/usr/lib/python3.8/importlib/__init__.py",line 127,in import_module
05:55:03 return _bootstrap._gcd_import(name[level:],package,level)
05:55:03 File"/app/calibre-web/cps/metadata_provider/NewDouban.py",line 7
05:55:03 <!DOCTYPE html>
05:55:03 A
05:55:03 SyntaxError:invalid syntax

**Comment by fugary** [comment]
请确认下下载的文件内容是不是python代码

**Comment by toniexly** [comment]
> 请确认下下载的文件内容是不是python代码

哦果然不对。。第一行filetype html....我研究下

解决了哈。
