### ISSUE TITLE
关于封面的问题

### ISSUE THREAD

**Issue by hprandom** [fugary/calibre-web-douban-api#8]
我使用豆瓣获取图书信息后，在封面那一览会自动填入封面网址信息，但是每次都会出现错误提示：

“You are not allowed to access localhost or the local network for cover uploads”

但同时也提示：已成功更新元数据

如果把封面那一栏留空，就不会出现这个。
请问这是什么问题？是我哪里没有设置好吗？

补充一下，上传电脑中的图片就没有这样的问题。

**Comment by fugary** [comment]
你是什么版本的calibre-web？
另外填入的地址是这样的格式https://img1.doubanio.com/view/subject/l/public/xxxxx.jpg吧？

**Comment by hprandom** [comment]
我的calibre-web是最新的0.6.18版，用的是这个docker：https://github.com/gshang2017/docker/tree/master/calibre-web
刚才试了一本书，地址是：https://img2.doubanio.com/view/subject/l/public/s28063701.jpg
![image](https://user-images.githubusercontent.com/48062021/167352013-b6803b05-09fc-4ae9-bf21-483a87d2d1ae.png)

点击最下方的保存后，就出现如下图：
![image](https://user-images.githubusercontent.com/48062021/167352243-6c64489d-4cb8-46c9-9b7d-f2d48bc0b378.png)

除了封面，其他都保存成功了。

**Comment by fugary** [comment]
你这个地址看起来没有问题，这种错误是calibre-web报出来的，是检测到封面地址是本地回环地址报错：You are not allowed to access localhost for cover uploads，calibre-web服务有使用代理或者VPN啥的吗？

**Comment by hprandom** [comment]
谢谢回复。有是有代理，但是软路由上理论上应该自动分流直连了啊……

我应该去NAS还是软路上看这个图片网址有没有正确反馈？
